version: '2'
services:
  postgres:
    container_name: postgres-quotes
    image: 'postgres:latest'
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
    ports:
      - '5455:5432'